### ISSUE TITLE
why do u use R2DBC 

### ISSUE THREAD

**Issue by fizz12344321** [gudzpoz/r2dbc-jdbc#16]
Hi, i am reading your project and i am interested in this, but i have a question, why do you use R2DBC instead of other non blocking IO like Hibernate Reactive or others... can you tell me your purpose, the pros and cons of R2DBC, thank you so much

**Comment by gudzpoz** [comment]
I suggest that you consult the authors and other users of R2DBC at, for example, [their Gitter community](https://gitter.im/R2DBC/r2dbc) or [Google Groups](https://groups.google.com/g/r2dbc).

This project is just a third-party SPI implementation of R2DBC and your question is quite irrelevant to this repository.
